name: bulid 4 package

on:
 workflow_dispatch:
  push:
    tags:
      - v*.**

jobs:
  build:
    name: Build ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - arm_cortex-a5_neon-vfpv4
          - arm_cortex-a7
          - arm_cortex-a7_neon-vfpv4
          - x86_64

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build
        uses: sbwml/openwrt-gh-action-sdk@go1.21
        env:
          ARCH: ${{ matrix.arch }}-openwrt-23.05
          FEEDNAME: packages_ci
          PACKAGES: luci-app-homeproxy
          NO_REFRESH_CHECK: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ matrix.arch }}
          path: bin/packages/${{ matrix.arch }}/packages_ci/*.ipk

      - name: Zip ipk packages
        run: |
          zip -j ${{ matrix.arch }}.zip bin/packages/${{ matrix.arch }}/packages_ci/*.ipk
          echo -e "**文件说明** 🎈:\n" >> release.txt
          echo -e "1. 默认homeproxy的插件与依赖整合包\n" >> release.txt
          echo -e "2. 使用方法：将整合包上传到openwrt设备的tmp目录，输入命令 \`opkg install *.ipk\`\n" >> release.txt
          echo -e "3. 默认压缩包里包含homeproxy插件\n" >> release.txt
          echo -e "4. 单独安装luci-app-homeproxy上传到openwrt设备的tmp目录,输入命令 \`opkg install *.ipk\`\n" >> release.txt
          
      - name: Create Release zip
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          artifacts: "${{ matrix.arch }}.zip,bin/packages/${{ matrix.arch }}/packages_ci/*.ipk"
          allowUpdates: true
          replacesArtifacts: true
          bodyFile: "release.txt"
          tag: v3.1.${{ github.run_number }}_${{ matrix.arch }}

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 6
          keep_minimum_runs: 0
    
      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: 28
          delete_tags: true
        env:
           GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
